TACC/Core-CMS-Resources

frontera-cms/static/frontera-cms/css/archive/main.frontera.css
Update URLs to Frontera archive fonts (no longer in `site_cms`).
=> Quick: Frontera CMS: Fix old URLs to archive fonts

3dem-org/secrets.py, example-cms/secrets.py, frontera-cms/secrets.py, neuronex-cms/secrets.py, texascale-org/secrets.py
- Enable new guide templates for portal CMS's.
- Enable new templates for `example-cms` (for demo purposes).
- Disable outdated Texascale templates.
=> Quick: FP-893/FP-977: Support new templates

neuronex-cms/secrets.py
Fix boolean value for `neuronex-cms` setting.
This is a noop, because the change is to a static file that is currently _only_ for manual reference. And the person referencing the file — @rstijerina — knows the correct value.
=> Quick: Fix neuronex setting

neuronex-cms/secrets.py
Add missing entry for "Standard Portal Homepage" to `neronex-cms`'s `secrets.py` "manual patch file".
=> Quick: Add home template to neuronex-cms secrets

example-cms/static/example-cms/css/src/_imports/generic/roots.css, neuronex-cms/static/neuronex-cms/css/src/_imports/generic/roots.css, protx-cms/static/protx-cms/css/src/_imports/generic/roots.css
Remove warning background color from the newest sites' starter CSS.
> Also, fix typos and add comment about purpose of this awful background color.
0. Follow [Test New CMS Site](https://github.com/TACC/cms-site-resources/wiki/Test-New-CMS-Site) instructions.
1. (In Step 2 of [Test New CMS Site](https://github.com/TACC/cms-site-resources/wiki/Test-New-CMS-Site)) Set CMS to run as `neuronex-cms` or `protx-cms`.
2. Load a page that uses `neuronex-cms` or `protx-cms`'s `fullwidth.html` template.
3. Ensure background is white.\*
_\* If background is not white, and you are testing with local image on local standalone CMS, be sure you run `npm run build`._
remote docker images:
- `taccwma/neuronex-cms:0dd0aa4`
=> Quick: Remove body bkgd warn color for new sites

core-cms/README.md
Support `core-cms` as `CUSTOM_ASSET_DIR` in image build configuration (even if Core has no assets).
> This will allow us to combine `dockerhub_repo` and `CUSTOM_ASSET_DIR` into one parameter.
- [FP-981](https://jira.tacc.utexas.edu/browse/FP-981)
0. Build new docker image using `core-cms` for both.
- You may use `taccwma/core-cms:7d3351b`.
0. Follow [Test New CMS Site](https://github.com/TACC/cms-site-resources/wiki/Test-New-CMS-Site) instructions.
- If testing on a local standalone CMS, be sure you're on the matching branch for [`Core-CMS`](https://github.com/TACC/Core-CMS).
1. (In Step 2 of [Test New CMS Site](https://github.com/TACC/cms-site-resources/wiki/Test-New-CMS-Site)) Set CMS to run as `core-cms`.
2. Load a page that uses the Core `fullwidth.html` template.
3. Ensure background …
=> Quick: Add empty Core cms directory

frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-home.css
Import truncate mixin where it is used _i.e. do not rely on it having been included earlier._
- https://github.com/TACC/Core-CMS/pull/199
- __Fix__: Import `x-truncate` mixin from tools in file that relies on it.
There will be a build output difference: some code has moved from bottom of stylesheet to top of stylesheet. This movement does not affect the page styles. I tested on https://frontera-portal.tacc.utexas.edu/home-2021-03/.
<details><summary>the code that moves</summary>
`.s-article-preview p:not(:first-child):not(:last-child),.s-home__banner .o-section__banner-overlay p,.x-truncate--many-lines{--lines:2;display:-webkit-box;-webkit-box-orient:vertical;overflow:hidden;-webkit-line-clamp:var(--lines)}.x-untruncate--many-lines{overflow:visible;-webkit-line-clamp:inherit}.s-article-pre …
=> Quick: Import missing CSS tool

frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-home.css
See https://github.com/TACC/Core-CMS/pull/218.
Update path to new directory for any files previously in Core's `site_shared`.
=> (from Core) Quick: Deprecate site_shared

frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-header.css, frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-search-bar.css, frontera-cms/static/frontera-cms/css/src/site.header.css
Changes for Frontera based on Core changes.
https://github.com/TACC/Core-CMS/pull/225
- _Minor_: Add commented code for logo width (can not use yet, see comment).
- _Minor_: Remove now-unnecessary `em` font sizes for `<tacc-search-bar>`.
- _Minor_: Load new Frontera header stylesheet.
=> Frontera: Core-CMS#255 Navigation Bar

frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-home.css
Set image position and size to match design, and let them be constant.
At screen width 1200px, Frontera hero banner image should match design as close as possible.
- Design: [Frontera Prod Home 2021-03](https://frontera-portal.tacc.utexas.edu/home-2021-03/)
- Test Page: [Frontera Redesign](https://xd.adobe.com/view/90e6b252-0293-4243-7748-11d94a0763d0-e6d7/specs/)
At other screen widths, image must always take up full width of page.
=> Hotfix: GH-233: Frontera hero image position

frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-home.css
Frontera: Fix bugs with outline on hover over articles in banner.
- Ensure equal padding so `outline` behaves (in Firefox & Safari).
- Ensure caption is visible (in Firefox).
- Check hover outline at all screen sizes on Firefox and Safari.
1. On wide screen, outline extends too far to the right. This is fixed in a commit in Core.
=> Hotfix: GH-233: Frontera hero article hover bugs

frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-search-bar.css
To support https://github.com/TACC/Core-CMS/pull/231/, remove Portal-specific font sizes from a stylesheet that is not loaded on Portal.
Merge __after__ https://github.com/TACC/Core-CMS/pull/231/ is merged.
=> GH-230: Remove moot Frontera search font sizes

texascale-org/static/texascale-org/css/src/_imports/elements/html-elements.css, texascale-org/static/texascale-org/css/src/template.article.image-map.css
Easily fix two bugs on Texascale.org after testing it against Core using new GitHub repo and the latest code.\*
> \* Dev server was _previously_ using GitLab repo. Prod server is _still_ using GitLab repo (not for long, now).
1. __Fix__: Remove borders from Texascale tables
2. __Fix__: Load Core Image Map component for Texascale
- Ensure homepage has no borders on section separators.
- Ensure [Frontera Secret Sauce (dev)](https://texascale-dev.tacc.utexas.edu/2020/visualizing-science/frontera-secret-sauce/) looks like [prod](https://texascale.org/2020/visualizing-science/frontera-secret-sauce/).
- Ensure [What's In a Node? (dev)](https://texascale.tacc.utexas.edu/2019/visualizing-science/whats-in-a-node/) looks like [prod](https://texascale.org/2019/visualizing-science/whats-in-a-node/).
=> Quick: Remove table border from homepage

a2cps-cms/secrets.py, a2cps-cms/templates/fullwidth.html
- https://github.com/TACC/Core-CMS/pull/272 is dependent on this PR.
- Add missing template.
- (I forgot to push this commit into https://github.com/TACC/Core-CMS-Resources/pull/57 before merge.)
- Update a couple incorrect secrets values.
1. Open https://pprd.a2cps.tacc.utexas.edu/.
2. ✓ Ensure logo is loaded.
3. ✓ Ensure A2CPS "Fullwidth" template is available.
4. Choose A2CPS "Fullwidth" template.
5. ✓ Ensure stylesheet `/static/a2cps-cms/css/build/site.css` is loaded.
- Stylehsheet is empty. This is accurate.
6. ? Ensure Google Analytics is loaded.
=> Quick: A2CPS Template

a2cps-cms/templates/fullwidth.html, a2cps-cms/templates/standard.html, frontera-cms/templates/home.html, protx-cms/templates/fullwidth.html, protx-cms/templates/standard.html, utrc-cms/templates/fullwidth.html, utrc-cms/templates/standard.html
Add `super` blocks to `assets_custom` blocks that should have it.
Closes #81.
Custom Favicon (UTRC)*
Standard Favicon† (Frontera)
> \* This screenshots shows new UTRC logo, because I was also testing #83.
> † Though this is a standard favicon, the favicon is not in default location browser looks, so it should be tested.
0. Ensure favicon is not cached for test. Options:
- ✅ Visit a project URL with a favicon you have not tried to load. _— confirmed_
- ❓ Load local site with new URL or port. _— unconfirmed_
- ⚠️ [Clear your browser's favicon cache](https://www.google.com/search?q=remove+favicon+cache) _— ha ha, good luck_
1. Load CMS using any of these "Project, Template" combinations:
- A2CPS, Fullwidth
- A2CPS, Standard
- Frontera, Home
- ProTX, Fullwidth
- ProTX, Standard
- __UTRC, …
=> GH-81: Fix Favicons Not Loading

texascale-org/settings_custom.py, texascale-org/urls.py
Commit fixes that were tested on Texascale after FP-1194 removed the Blog from Core.
Tested on https://texascale-dev.tacc.utexas.edu/ following [(Stand-Alone) CMS Deployment Update](https://confluence.tacc.utexas.edu/display/UP/CMS+Deployment+Update) (and its missing steps).
- The diff matches that of `task/GH-73-tacc-blockquote-plugin`...`task/GH-73-tacc-blockquote-plugin--after-FP-1194` ([temporary live diff link](https://github.com/TACC/Core-CMS-Resources/compare/task/GH-73-tacc-blockquote-plugin...task/GH-73-tacc-blockquote-plugin--after-FP-1194)).
- I am merging this already-tested fix so that https://github.com/TACC/Core-CMS-Resources/pull/61 can be merged isolated from this fix.
=> Hotfix: Texascale: Post-FP-1194 Fix (Restore Blog)

brainmap-cms/settings_custom.py
Fix SGCI image to link to SGCI site, not NSF.
- https://github.com/TACC/Core-CMS/pull/398
=> Hotfix: BM-5/BM-19: Fix link to SGCI (was NSF)

texascale-org/static/texascale-org/css/src/_imports/components/deprecated/c-offset-content.css
- https://github.com/TACC/Core-CMS/pull/406
Ensure `c-offset-content` elements are full width on narrow windows.
[FP-1338](https://jira.tacc.utexas.edu/browse/FP-1338)
| Narrow Window | Wide Window |
| - | - |
| ![Narrow Window](https://user-images.githubusercontent.com/62723358/141350606-7d0b190d-1f2a-452a-a5f1-d3d2055b2ebc.png) | ![Wide Window](https://user-images.githubusercontent.com/62723358/141350603-b445e6f3-031e-490c-b881-28c51a568307.png) |
1. Open https://texascale-dev.tacc.utexas.edu/2020/feature-stories/twisted-physics/.
2. On wide window, find offset content (content offset from flow of article text).
3. Ensure offset content:
- _does **not**_ span 100% of container
- is offset
- text wraps around one end of it
4. On narrow window, find the content that was offset (it should …
=> Hotfix/FP-1338: Offset Content to be Full Width on Narrow Window

frontera-cms/templates/standard.html
- https://github.com/TACC/Core-CMS/pull/401
Ensure favicon loads on Frontera standard template.
1. Load https://pprd.frontera-portal.tacc.utexas.edu/system. [^0]
1. Verify favicon is a black field with a gray longhorn head.
- **not** a white star on blue gradient
- **not** a blue favicon with the word TACC
2. Verify favicon URL in markup is `/static/frontera-cms/img/org_logos/favicon.ico`.
[^0]: Deployed via https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/849/ which loads image from CMS branch `main--v3-3-0-with-hotfixes`.
[FP-1330](https://jira.tacc.utexas.edu/browse/FP-1330)
=> Hotfix/FP-1330: Frontera: Fix Favicon Load on Standard Template

utrc-cms/static/utrc-cms/css/src/_imports/trumps/s-home.css
Remove white border under header in utrc.
* [FP-1422](https://jira.tacc.utexas.edu/browse/FP-1422)
Overrided the `.o-section__banner-image` style for utrc.
1. Ensure that the white border doesn't show with the utrc layout locally.
<details>
<summary>Local layout I tested with</summary>
</details>  
2. Ensure that this change doesn't affect other UI elements.
<details>
<summary>What was the core issue?</summary>
There seems to be some monkey business between the:
- `rem` height of `.s-home__banner` [overrided by utrc](https://github.com/TACC/Core-CMS-Resources/blob/1987e4eb2c5f31140b78d806ee3698215aec4047/utrc-cms/static/utrc-cms/css/src/_imports/trumps/s-home.css#L43) in `/utrc-cms/static/utrc-cms/css/src/_imports/trumps/s-home.css` and the `transform` and
- `top` of the …
=> Bug/FP-1422: Remove white border under header.

frontera-cms/templates/home.html, utrc-cms/static/utrc-cms/css/src/_imports/trumps/s-home.css, utrc-cms/templates/home.html
- https://github.com/TACC/Core-CMS/pull/433
- Solve section overflow in `o-section` code (not in templates).
- Use simpler CSS (for code related to code in [#433](https://github.com/TACC/Core-CMS/pull/433) that also got simplified).
=> FP-1318: Revisit Section Pattern (Frontera) (UTRC)

utrc-cms/settings_custom.py, utrc-cms/templates/fullwidth.html, utrc-cms/templates/standard.html
Remove deprecated UTRC templates.
1. Confirm these pages can load:
- [(pre-prod) `/publications/`](https://utrc.tacc.utexas.edu/publications/)
- [(pre-prod) `/about/`](https://utrc.tacc.utexas.edu/about/)
3. Confirm styles match those on prod:
- [(prod) `/publications/`](https://utrc.tacc.utexas.edu/publications/)
- [(prod) `/about/`](https://utrc.tacc.utexas.edu/about/)
UTRC pprd and prod pages have been updated to use new templates.
=> Quick: (UTRC-357/FP-1268) Remove old templates

utrc-cms/static/utrc-cms/css/src/_imports/trumps/s-home.css
Fix a typo and neglected style that led to vertical space instead of horizontal space.
Also, reduce over-specificity.
- __[FP-1525](https://jira.tacc.utexas.edu/browse/FP-1525)__
- Review Ticket: [FP-1529](https://jira.tacc.utexas.edu/browse/FP-1529)
|  | 576px | 768px | 992px | 1200px | 1400px | 1680px |
| - | - | - | - | - | - | - |
| Broken | — | — | ![UTRC Home Broken FP-1525 992px](https://user-images.githubusercontent.com/62723358/155621369-73d31814-f61d-4b78-8693-175b8bbc016a.jpeg) | ![UTRC Home Broken FP-1525 1200px](https://user-images.githubusercontent.com/62723358/155621373-0fa86324-4ffa-420a-bead-db8a9bed406a.jpeg) | — | — |
| Fixed | ![UTRC Home Stage 576px](https://user-images.githubusercontent.com/62723358/155621096-da3e9d86-5a19-4c5c-aa99-35985d9f2109.jpeg) | ![UTRC Home …
=> FP-1525: UTRC: Fix Homepage Whitespace

example-cms/README.md
Polish `example-cms/` README (to reduce diff of unrelated new PR where I made the same change).
=> Noop: Polish Example CMS Readme

utrc-cms/static/utrc-cms/css/src/_imports/trumps/s-home.css
I noticed text-size CSS had typo, so it wasn't applied. I fix it.
- UTRC homepage focus list text size will match the text size of h2 above it.
The focus list is intend to look like a continuation of the h2, albeit still as content, not as the title proper.
=> Quick: UTRC: Fix Homepage Focus List Text Size

texascale-org/static/texascale-org/css/src/_imports/elements/html-elements.css, texascale-org/static/texascale-org/css/src/page.dispatches-frontera.css
Remove legacy selectors.
- https://github.com/TACC/Core-CMS-Resources/issues/25
- requires https://github.com/TACC/Core-CMS/pull/151
- Delete legacy part of Texascale CSS selectors.
- (Unrelated) Rename a suggested classname.
=> GH-149: Updates for TACC/Core-CMS#149 (base.html polish)

tup-cms/settings_custom.py
Do not enable LDAP for TUP CMS.
_Because J.Y. said not to… I believe because Portal will mediate LDAP auth via single-sign-on, and new TUP CMS does not need all staff to be able to be users._
- https://github.com/TACC/Core-CMS/pull/499
(skipped)
- set LDAP setting to false
=> feat(tup): no LDAP (Portal will manage users)

a2cps-cms/static/a2cps-cms/css/src/_migrations/v1_v2/a2cps.css
Do not unset footer margin that is now never added (as of [TACC/Core-CMS#506](https://github.com/TACC/Core-CMS/pull/506)).
- [FP-1665](https://jira.tacc.utexas.edu/browse/FP-1665)
- requires https://github.com/TACC/Core-CMS/pull/506
- do not unset footer margin (64be2e2)
</details>
See https://github.com/TACC/Core-CMS/pull/506.
=> After/tup 271 fp 1665 submod changes (a2cps migration css tweak)

protx-cms/static/protx-cms/css/.postcssrc.yml, tup-cms/static/tup-cms/css/.postcssrc.yml
Update outdated paths to core-styles theme configs.
- Verify [ProTX (pre-prod)](https://pprd.protx.tacc.utexas.edu/) no longer has a giant white header (should be split black and gray normal-size header).
- TUP change (near identical) not tested on dev server, because it has older release not ready for update.
=> After/tup 271  hotfix core styles theme path

ecep-cms/static/ecep-cms/css/src/site.css
Provide full suite of global accent colors for `ecep-cms`.
- [FP-1499](https://jira.tacc.utexas.edu/browse/FP-1499) (tangentially… see testing)
- added color vars
- added organizational core-cms comments
- removed detailed core-cms comments
Tested during development of https://github.com/TACC/Core-CMS/pull/512.
=> fix(ecep-cms): global accent colors full suite

frontera-cms/static/frontera-cms/css/src/_imports/trumps/s-home.css, utrc-cms/static/utrc-cms/css/src/_imports/trumps/s-home.css
Adapt `.s-home__banner` selectors to new markup.
_I changed the markup slightly in dev and pprd.[^1]_
[^1]: For details, see https://github.com/TACC/Core-CMS/pull/513.
- [FP-1723](https://jira.tacc.utexas.edu/browse/FP-1723)
- required by https://github.com/TACC/Core-CMS/pull/513
See https://github.com/TACC/Core-CMS/pull/513.
=> chore(frontera, utrc): fp-1723 selectors for new markup

ecep-cms/static/ecep-cms/css/src/site.css
Hide byline for news on ECEP, for article **and** article list.
- required by https://github.com/TACC/Core-CMS/pull/519
- fixes https://github.com/TACC/Core-CMS-Resources/pull/154
- explicit selectors
- specific selectors
See https://github.com/TACC/Core-CMS/pull/519
Previous attempt (https://github.com/TACC/Core-CMS-Resources/pull/154) was too simple.
=> fix(ecep): tup-151: hide "by: " line, stronger

ecep-cms/static/ecep-cms/css/src/app.blog.css, ecep-cms/templates/snippets/site-css.html
CSS that is only in `site/ecep/main` but relied on by prod.
<details>The CSS should have been in a branch/PR (or at least a main commit), but I seem to have made the commits directly to `site/ecep/main`. Bad Wes.</details>
- [fix(ecep): load blog custom selectors](https://github.com/TACC/Core-CMS-Resources/commit/2435456fa3720d5462a15312eb776f6b8f4c95fd)
- [feat(ecep): simplify project-specific css](https://github.com/TACC/Core-CMS-Resources/commit/63601f9c50f33ed0411744624e952c8046b677f1)
- [feat(ecep): project-specific blog css](https://github.com/TACC/Core-CMS-Resources/commit/ccf21cf591c3132adcb1d37692c13e4e1621b4dc)
=> fix(ecep-113): ecep blog css from site/ecep/main

brainmap-cms/settings_custom.py
BrainMap logo should link to home page, not an external site.
- change URL in an array for brainmap logo setting
1. Verify logo (yellow line globe) at https://pprd.brainmap.tacc.utexas.edu/guides/getting-started/ navigates to home page.
N/A
Source: https://jira.tacc.utexas.edu/browse/BM-35?focusedId=25954&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25954
=> feat(bm): FP-1798 link logo to home not ext site

apcd-cms/settings_custom.py
Do not add default e-mail settings.
- [FP-1823](https://jira.tacc.utexas.edu/browse/FP-1823)
- requires https://github.com/TACC/Core-CMS/pull/550
- mirrored by https://github.com/TACC/Core-CMS-Custom/pull/7
- remove hard-coded remote e-mail host
- add comment to direct developer to instructions
See https://github.com/TACC/Core-CMS/pull/550.
=> fix(settings): fp-1823 do not define email settings

brainmap-cms/settings_custom.py
Add text to logo that should have it.
- fixes [BM-41](https://jira.tacc.utexas.edu/browse/BM-41)
- fixes text neglected in #170
- restores text from #167
- **changed** logo file path
1. Verify logo has text "BRAINMAP.ORG".
https://github.com/TACC/Core-CMS-Resources/assets/62723358/c26ed8a1-8cc4-4b95-82a8-e01d74bad183
=> fix(brainmap): bm-41 logo should have text

README.md, a2cps-cms/templates/fullwidth.html, a2cps-cms/templates/standard.html, a2cps_cms/settings_custom.py, docs/upgrade-project.md, frontera-cms/templates/fullwidth.html, frontera-cms/templates/home.html, frontera-cms/templates/standard.html, frontera_cms/settings_custom.py
Fix server crash since https://github.com/TACC/Core-CMS/releases/tag/v3.12.0-alpha.10.
- required by https://github.com/TACC/Core-CMS/pull/676
- **added** `frontera-cms` template redirects
1. Build CMS image.
2. Deploy CMS image.
3. Access website.
4. Check whether site loads or crashes.
Just visit website ツ.
The fixes alone seem **not** adequate for a CMS at v3.12 **and** on https://github.com/TACC/Core-CMS-Custom. Example: 
- https://github.com/TACC/Core-CMS-Custom/pull/175 — 2023-07-25
=> fix: v3.12.0-alpha.10 crash (add template redirects)

apcd_cms/static/apcd_cms/css/src/placeholder.css
Delete APCD directory, because it was built at https://github.com/TACC/Core-CMS-Custom/tree/main/apcd-cms.
It's directory in Core-CMS is an unexplained leftover.
- https://github.com/TACC/Core-CMS/pull/690
=> chore: delete apcd (migrated to Core-CMS-Custom)

protx-cms/README.md, protx-cms/templates/getting_started.html, protx_cms/settings_custom.py
Allow deploy of ProTX on CMS v3.12. Support deprecated template.
- **added** old template path redirect, setting, and doc
1. Verify website has same styles as prod.
2. Verify "Getting Started" template works.
3. Verify "Getting Started" template is clearly marked as "DEPRECATED".
=> feat(protx): v3.12 support i.e. support deprecated templates

example_cms/urls.py
[Creating new post via `example_cms` causes error because of missing `urls.py` tweak.](https://github.com/nephila/djangocms-blog/issues/81#issuecomment-1819497693)
- coupled to https://github.com/TACC/Core-CMS/pull/750
- **added** missing `urls.py` file/tweak
Skipped. Familiar mistake. Easy fix.
=> hotfix(example_cms): missing urls.py

README.md, frontera_cms/static/frontera_cms/css/src/_migrations/v1_v2/frontera.css, utrc-cms/templates/home.html, utrc_cms/settings_custom.py, utrc_cms/static/utrc_cms/css/src/_imports/trumps/s-home.css
Edit CSS so that Django and Vite do not use it unexpectedly.
- [TUP-677](https://tacc-main.atlassian.net/browse/TUP-677)
<details><summary>Pull Requests</summary>
- https://github.com/TACC/tup-ui/pull/400 requires:
- https://github.com/TACC/Core-Styles/pull/285
- https://github.com/TACC/Core-CMS/pull/780 requires:
- https://github.com/TACC/Core-Styles/pull/285
- https://github.com/TACC/Core-CMS-Resources/pull/197
</details>
- **refactored** comments that suggest to `@import` code
- **refactored** absolute `/static` paths to be relative
- **documented** additional parameter for `collectstatic` command
0. **Uncertain.** See https://github.com/TACC/tup-ui/pull/398.
1. Verify the custom fonts Frontera uses (on it's old-style pages) still load e.g.:
- …
=> chore: tup-677 css/django/vite interoperability

brainmap_cms/static/brainmap_cms/css/src/site.css, frontera_cms/static/frontera_cms/css/src/_imports/settings/color.css, frontera_cms/static/frontera_cms/css/src/_imports/trumps/s-home.css, utrc_cms/static/utrc_cms/css/src/_imports/trumps/s-home.css
Do **not** use `-rgb` CSS variables. Update `%x-overlay` usage. Deprecate `alt`/`weak` colors.
- requires https://github.com/TACC/Core-Styles/pull/372
- required by https://github.com/TACC/Core-CMS/pull/863
- **documented** deprecated colors
- **changed** `%x-overlay` to override latest properties
- **changed** `%x-overlay` usages to use design tokens
Verify homepage `%x-overlay` usage's color and opacity are unchanged on:
Skipped.
=> enhance: CMD-182 design tokens

_3dem_cms/templates/fullwidth.html, texascale_cms/templates/fullwidth.html
Explicitly do **not** show breadcrumbs since https://github.com/TACC/Core-CMS/pull/870.
- **added** code to hide breadcrumbs
<details><summary>Reasoning</summary>
In Core-CMS, breadcrumbs become their own block. Until now, `fullwidth.html` templates of a custom CMS have implicitly had no breadcrumbs. To continue to **not** show breadcrumbs, these templates must:
- **either** explicitly hide breadcrumbs
- **or** extend Core-CMS `fullwidth.html`
I am more comfortable performing the former without testing. The latter is more appropriate but requires testing (which requires many steps and documenting) and would be moot if I can migrate the CMS's to Core-CMS-Custom ([WP-197](https://tacc-main.atlassian.net/browse/WP-197)) without a custom template (as I have done for some migrated CMS's). …
=> fix: do not show breadcrumbs since Core-CMS#870

_3dem_cms/templates/fullwidth.html, texascale_cms/templates/fullwidth.html
Explicitly do **not** show breadcrumbs since https://github.com/TACC/Core-CMS/pull/870.
- **updated** code to hide container (and breadcrumbs)
- continues #201
=> fix: do not show container since Core-CMS#870

_3dem_cms/templates/fullwidth.html, texascale_cms/templates/fullwidth.html
Remove `{% block title %}`, because CMS will set it properly in `base.html`.
- **removed** now-redundant block
Skipped.
=> refactor: no need to redefine title block

texascale-org/templates/article.freeform.html, texascale-org/templates/article.html, texascale-org/templates/article.image-map.html, texascale-org/templates/article.sidebar-right.html, texascale-org/templates/article.visual.html, texascale-org/templates/category.html, texascale-org/templates/fullwidth.html
Delete deprecated templates unused since https://github.com/TACC/Texascale-CMS/pull/5.
- https://github.com/TACC/Texascale-CMS/pull/5
=> chore: delete deprecated templates
